# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/trusty64"
   config.vm.provision :shell, path: "config/prov_files/prov.sh"
   config.vm.network :forwarded_port, guest: 80, host: 4567
   config.vm.network "private_network", ip: "192.168.50.69"
   config.vm.hostname = "lamp-1"
   config.vm.synced_folder "/Users/RomanRheingans/documents/projects/health_record/html", "/var/www/html/"
end
